# Generated by Django 3.1.4 on 2020-12-17 06:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('customer', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_name', models.CharField(blank=True, max_length=200, null=True)),
                ('from_date', models.DateField(blank=True, null=True)),
                ('balance_to', models.DateField(blank=True, null=True)),
                ('proid', models.IntegerField(default=0)),
                ('tyear', models.IntegerField(blank=True, null=True)),
                ('Invoice_no', models.CharField(blank=True, max_length=30, null=True)),
                ('invoice_amount', models.DecimalField(blank=True, decimal_places=3, max_digits=19, null=True)),
                ('notes', models.CharField(blank=True, max_length=200, null=True)),
                ('balance', models.DecimalField(blank=True, decimal_places=3, max_digits=19, null=True)),
                ('commited', models.BooleanField(default=False)),
                ('imported_date', models.DateTimeField(auto_now=True, null=True)),
                ('customer_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customer.customer')),
            ],
        ),
    ]
