# Generated by Django 3.1.4 on 2020-12-24 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='proid',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
