# Generated by Django 3.1.4 on 2020-12-04 21:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='invoice',
            name='upload_date',
        ),
    ]
