# Generated by Django 3.1.4 on 2020-12-05 05:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0003_auto_20201205_0003'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='balance_to',
            field=models.DateField(blank=True, null=True),
        ),
    ]
