# Generated by Django 3.1.4 on 2020-12-05 05:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0004_auto_20201205_0714'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='invoice_amount',
            field=models.DecimalField(blank=True, decimal_places=3, default=0.0, max_digits=7, null=True),
        ),
    ]
