# Generated by Django 3.1.4 on 2020-12-05 06:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0006_auto_20201205_0810'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='from_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
