# Generated by Django 3.1.4 on 2020-12-05 06:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0007_invoice_from_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='balance_to',
            field=models.DateField(blank=True, null=True),
        ),
    ]
