# Generated by Django 3.1.4 on 2020-12-05 06:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0008_invoice_balance_to'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='proid',
            field=models.IntegerField(default=0),
        ),
    ]
