# Generated by Django 3.1.4 on 2020-12-05 06:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0009_invoice_proid'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='Invoice_no',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
