# Generated by Django 3.1.4 on 2020-12-05 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0011_invoice_invoice_amount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='invoice_amount',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=19, null=True),
        ),
    ]
