# Generated by Django 3.1.4 on 2020-12-05 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0012_auto_20201205_0856'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='notes',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
