# Generated by Django 3.1.4 on 2020-12-05 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0013_invoice_notes'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='balance',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=19, null=True),
        ),
    ]
