# Generated by Django 3.1.4 on 2020-12-05 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0014_invoice_balance'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='commited',
            field=models.BooleanField(default=False),
        ),
    ]
