# Generated by Django 3.1.4 on 2020-12-06 05:40

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0015_invoice_commited'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='imported_date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
