# Generated by Django 3.1.4 on 2020-12-11 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0016_invoice_imported_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='imported_date',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
