# Generated by Django 3.1.4 on 2020-12-11 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0017_auto_20201211_0918'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='imported_date',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
