# Generated by Django 3.1.4 on 2020-12-11 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0018_auto_20201211_0930'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='tyear',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
