# Generated by Django 3.1.4 on 2020-12-24 05:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='beginig_balance',
            field=models.DecimalField(blank=True, decimal_places=3, default=0, max_digits=19, null=True),
        ),
    ]
