# Generated by Django 3.1.4 on 2020-12-18 08:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Treasury',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('treasury_name', models.CharField(max_length=200)),
                ('beginig_balance', models.DecimalField(blank=True, decimal_places=3, default=0, max_digits=19, null=True)),
                ('is_active', models.BooleanField(blank=True, default=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trans_date', models.DateField(auto_now=True)),
                ('trans_amount', models.DecimalField(decimal_places=3, max_digits=19)),
                ('trans_desc', models.CharField(blank=True, max_length=250, null=True)),
                ('created_date', models.DateTimeField(auto_now=True)),
                ('update_date', models.DateTimeField(auto_now_add=True, null=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('treasury', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='treasury.treasury')),
            ],
        ),
    ]
