# Generated by Django 3.1.4 on 2020-12-09 20:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Receipt',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('receipt_no', models.IntegerField()),
                ('receipt_date', models.DateTimeField()),
                ('receipt_amount', models.DecimalField(decimal_places=3, max_digits=19)),
                ('receipt_notes', models.CharField(blank=True, max_length=250, null=True)),
                ('receipt_created', models.DateField(auto_now_add=True)),
            ],
        ),
    ]
