# Generated by Django 3.1.4 on 2020-12-20 20:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('casa', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='receipt',
            old_name='customer_id',
            new_name='customer',
        ),
        migrations.RemoveField(
            model_name='receipt',
            name='customer_name',
        ),
    ]
