# Generated by Django 3.1.4 on 2020-12-12 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('casa', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='receipt',
            name='customer_id',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='receipt',
            name='customer_name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
