# Generated by Django 3.1.4 on 2021-01-09 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('casa', '0002_auto_20201220_2209'),
    ]

    operations = [
        migrations.AddField(
            model_name='receipt',
            name='priod',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='receipt',
            name='syear',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
