# Generated by Django 3.1.4 on 2021-01-17 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('casa', '0005_auto_20210117_0933'),
    ]

    operations = [
        migrations.AddField(
            model_name='receipt',
            name='transfare_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
