# Generated by Django 3.1.4 on 2021-01-17 10:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('casa', '0006_receipt_transfare_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='receipt',
            old_name='transfare_msg_no',
            new_name='transfare_no',
        ),
    ]
