# Generated by Django 3.1.4 on 2021-01-18 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('casa', '0008_auto_20210118_1220'),
    ]

    operations = [
        migrations.AlterField(
            model_name='receipt',
            name='transfare_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
